### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Kadantte** [Shadowv7/LogsBot#2]
After getting the bot working I get this Error:
```shell
Error: Cannot find module '../functions'
Require stack:
- C:\Users\Candy\Desktop\covid-19\LogsBot\structures\Client.js
- C:\Users\Candy\Desktop\covid-19\LogsBot\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at new LogsBot (C:\Users\Candy\Desktop\covid-19\LogsBot\structures\Client.js:20:18)
    at Object.<anonymous> (C:\Users\Candy\Desktop\covid-19\LogsBot\main.js:7:12)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Candy\\Desktop\\covid-19\\LogsBot\\structures\\Client.js',
    'C:\\Users\\Candy\\Desktop\\covid-19\\LogsBot\\main.js'
  ]
}
(node:13140) UnhandledPromiseRejectionWarning: Error [SHARDING_READY_DIED]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (C:\Users\Candy\Desktop\covid-19\LogsBot\node_modules\discord.js\src\sharding\Shard.js:155:16)
    at Object.onceWrapper (events.js:428:26)
    at Shard.emit (events.js:321:20)
    at Shard._handleExit (C:\Users\Candy\Desktop\covid-19\LogsBot\node_modules\discord.js\src\sharding\Shard.js:371:10)
    at ChildProcess.emit (events.js:321:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
(node:13140) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 139)
```

and Here's my config.js:
```js
module.exports = {
	/* The token of your Discord Bot */
	token: "ma_boi_token",
}
```

**Comment by Shadowv7** [comment]
You need to make the functions.js file

**Comment by Kadantte** [comment]
Any example of it?

**Comment by Kadantte** [comment]
I just removed the line of the function just to test the Bot xD
line:
```js
this.stats = require("../functions");
```
![image](https://user-images.githubusercontent.com/11579313/77911142-3a73ae80-7288-11ea-89f5-2154d0a21f92.png)

**Comment by snowdqdzq** [comment]
hello can you help me?

(node:29616) UnhandledPromiseRejectionWarning: Error [SHARDING_READY_DIED]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (C:\Users\byswi\OneDrive\Bureau\LogsBot-master\node_modules\discord.js\src\sharding\Shard.js:155:16)
    at Object.onceWrapper (events.js:313:26)
    at Shard.emit (events.js:223:5)
    at Shard._handleExit (C:\Users\byswi\OneDrive\Bureau\LogsBot-master\node_modules\discord.js\src\sharding\Shard.js:371:10)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
(node:29616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was 
not handled with .catch(). (rejection id: 1)
(node:29616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.internal/modules/cjs/loader.js:305
      throw err;
      ^

Error: Cannot find module 'C:\Users\byswi\OneDrive\Bureau\LogsBot-master\node_modules\discord-logs\lib\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:297:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:528:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:27)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\byswi\OneDrive\Bureau\LogsBot-master\structures\Client.js:5:9)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\byswi\\OneDrive\\Bureau\\LogsBot-master\\node_modules\\discord-logs\\package.json',
  requestPath: 'discord-logs'
